spring:

  # mysql 连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #url: jdbc:mysql://localhost:3306/ssm_weibo?useUnicode=true&characterEncoding=UTF-8
      #url: jdbc:mysql://localhost:3306/movie_recommend_system_other?useUnicode=true&characterEncoding=UTF-8
      url: jdbc:mysql://localhost:3306/movie_recommend?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 1741074535zwk
      initial-size: 10
      min-idle: 10
      max-wait: 60000
      max-active: 100

#  # redis 配置
#  cache:
#    redis:
#      use-keyprefix: true
#      time-to-live: 1d
#  redis:
#      database: 0
#      host: 192.168.225.128
#      port: 6379
#      timeout: 6000ms
#      password:
#  #    集群环境打开下面注释，单机不需要打开
#  #    cluster:
#  #      集群信息
#  #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
#  #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
#  #      maxRedirects: 3
#      jedis:
#        pool:
#          max-active: 100
#          min-idle: 0
#          max-idle: 20
#          max-wait: -1
#
#  # RabbitMQ 配置
#  rabbitmq:
#    host: 192.168.225.128
#    port: 5672
#    username: zwk
#    password: zwk@123456
#    virtual-host: /
#    publisher-confirms: true
#
  # 视图解析器
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#      static-path-pattern: /static/**


#log4j日志
logging:
  file: log.log
  path: logs/
  level.com.zwk.movie_recommend: debug




